### ISSUE TITLE
Data not showing up anymore

### ISSUE THREAD

**Issue by deekoder** [minio/buzz#14]
localhost/:66 GET http://localhost:7000/vendors/bower_components/col-resizable/colResizable-1.6.min.js 
localhost/:67 GET http://localhost:7000/vendors/bower_components/datatables.net/js/jquery.dataTables.js 
localhost/:66 GET http://localhost:7000/vendors/bower_components/col-resizable/colResizable-1.6.min.js 
localhost/:67 GET http://localhost:7000/vendors/bower_components/datatables.net/js/jquery.dataTables.js 
functions.js:4 Uncaught TypeError: $(...).DataTable is not a function
    at HTMLDocument.<anonymous> (functions.js:4)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

**Comment by deekoder** [comment]
`brew install bower` and then `cd static/vendor` and then` bower install` fixes the issue.

**Comment by deekoder** [comment]
However docs need to be updated

**Comment by rushenn** [comment]
@deekoder Bower is included in package.json. `npm/yarn install` would do the job. I have already updated the doc to cover this in my PR.

**Comment by deekoder** [comment]
ok

**Comment by rushenn** [comment]
@deekoder Can we close this?
