### ISSUE TITLE
GetETA: Parse and display last ETA set for a given issue

### ISSUE THREAD

**Issue by deekoder** [minio/buzz#48]
Add an api called getETA for each issue #. Query the comment and parse for the string as set by getETA.

**Comment by ebozduman** [comment]
ETA: 2017-06-30 11:00

**Comment by ebozduman** [comment]
Testing

**Comment by ebozduman** [comment]
ETA: 2017-07-20 12:00

**Comment by ebozduman** [comment]
ETA: 2017-08-08 12:00

**Comment by ebozduman** [comment]
ETA: 2017-08-08 11:00

**Comment by kannappanr** [comment]
Don't have cycles to look into this right now.
