### ISSUE TITLE
State column needed for PR

### ISSUE THREAD

**Issue by deekoder** [minio/buzz#58]
Each PR has an overall state. If 3 reviewers are assigned, Each one of them hold a state variable which holds : Pending / Approved / Dismissed. Compute the overall state of a PR. A PR is approved only when all  reviewers have the state = approved.

**Comment by brendanashworth** [comment]
@deekoder so there's three states like this?:
- `Approved`, all reviewers have approved the current changes
- ` Pending Changes`, *any single* reviewer has requested changes
- `Pending Review`, a mix of reviewers `Pending` and `Approved`, or no reviewers set

**Comment by deekoder** [comment]
Sounds great brendan. We can have 4 states. The 3 you have here. And a 4th called "Not yet Reviewed" if there is no review activity.
